// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tywrkhghiosnekusmvxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5d3JraGdoaW9zbmVrdXNtdnhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA2NTQ0NDYsImV4cCI6MjA5NjIzMDQ0Nn0.fy0o5DJsNo4MHR-I2v5tp1VMBYgIeGzt4eYBsPJmDP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});